### ISSUE TITLE
Draft Proposal

### ISSUE THREAD

**Issue by JansenKat** [JansenKat/scooter-app#1]
Create basic proposal doc

**Comment by JansenKat** [comment]
idea -
1 route to display scooter data
1 route to display census data
1 route that takes a zipcode and shows data based on that

**Comment by skhan4321** [comment]
Ideas that show the cost based on distance (different routes)

**Comment by el-g0m3z** [comment]
All of the above! I think we can start small, get the basics done and then expand on routes/functionalities of each route.

**Comment by jljones78** [comment]
route that you can pass addresses,  show the results on a map,  calculate expected price
select a random ride and display on map
select top 10 routes and show on map

**Comment by erinbentley** [comment]
how would we get prices?

**Comment by jljones78** [comment]
It would be a few steps, maybe a little complicated, so that could be a stretch goal.  

It would look something like this:
turn start and end addresses to census tract
find all rides between those census tracts
calculate average time for those rides
multiply that time by $0.15/minute + $1 (the cost reported by Lime)

**Comment by JansenKat** [comment]
1 route = generate random # - display scooter ride
1 route = 2 addresses same zipcode, diff census track, how the data differs
1 route = input zipcode => % compaint, # rides in,m # rides out, max expense, min expense, avg, complaints, maps and other stats
1 route = input 2 addresses => price feature
1 route = display longest ride distance/time
1 route = rides that go nowhere, some plots on this. where/when
1 route = red zone zip code (10 worst neighbor hoods to leave scooter in)

Home route = description

find = shape file for zip codes

**Comment by jljones78** [comment]
Hi y'all, take a look at this draft proposal and let me know if you'd like any edits.

[Project Proposal - Draft.docx](https://github.com/JansenKat/scooter-app/files/4295957/Project.Proposal.-.Draft.docx)

**Comment by skhan4321** [comment]
I think this looks good
