### ISSUE TITLE
Front end differences on deployed app

### ISSUE THREAD

**Issue by el-g0m3z** [JansenKat/scooter-app#66]
- Deployed App does not "look" the same as when running locally

**Comment by JansenKat** [comment]
`Mixed Content: The page at 'https://scooterapp-dlhnw4ta6q-uc.a.run.app/' was loaded over HTTPS, but requested an insecure stylesheet 'http://scooterapp-dlhnw4ta6q-uc.a.run.app/static/dashboard.css'. This request has been blocked; the content must be served over HTTPS.
`
Here's the error message i see when I inspect. if this helps
